### ISSUE TITLE
FileNotFoundError on Linux

### ISSUE THREAD

**Issue by anitagraser** [Teakinboyewa/SpatialAnalysisAgent#21]
There seems to be an error in the path to the generated graph's html on Linux:

```
Error: [Errno 2] No such file or directory: './/home/anita/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SpatialAnalysisAgent-master/graphs/Buffer_Creation_solution_graph.html'
Traceback (most recent call last):
  File "/home/anita/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SpatialAnalysisAgent-master/SpatialAnalysisAgent_dockwidget.py", line 1298, in run
    exec(script_content, exec_globals, exec_locals)
  File "<string>", line 260, in <module>
  File "/home/anita/miniforge3/envs/qgis-ai/lib/python3.12/site-packages/pyvis/network.py", line 435, in save_graph
    self.write_html(name)
  File "/home/anita/miniforge3/envs/qgis-ai/lib/python3.12/site-packages/pyvis/network.py", line 536, in write_html
    with open(f"{tempdir}/{name}", "w+") as out:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './/home/anita/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SpatialAnalysisAgent-master/graphs/Buffer_Creation_solution_graph.html'
The script finished with errors.
```

The correct path would be: 

`/home/anita/.local/share/QGIS/QGIS3/profiles/default/python/plugins/SpatialAnalysisAgent-master/graphs/Buffer_Creation_solution_graph.html`

The "Workspace Directory" configured in "Settings" is ignored.

**Comment by bhf-love-lxy-forever** [comment]
I encountered the same problem

Error: [Errno 22] Invalid argument: './C:\\Users\\BHF\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\python\\plugins\\SpatialAnalysisAgent-master\\graphs\\Count_Elements_solution_graph.html'
Traceback (most recent call last):
  File "C:\Users/BHF/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SpatialAnalysisAgent-master\SpatialAnalysisAgent_dockwidget.py", line 1298, in run
    exec(script_content, exec_globals, exec_locals)
  File "<string>", line 260, in <module>
  File "C:\Users\BHF\miniconda3\envs\qgis\Lib\site-packages\pyvis\network.py", line 435, in save_graph
    self.write_html(name)
  File "C:\Users\BHF\miniconda3\envs\qgis\Lib\site-packages\pyvis\network.py", line 536, in write_html
    with open(f"{tempdir}/{name}", "w+") as out:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: './C:\\Users\\BHF\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\python\\plugins\\SpatialAnalysisAgent-master\\graphs\\Count_Elements_solution_graph.html'
The script finished with errors.

**Comment by bhf-love-lxy-forever** [comment]
temporary solution：

change network.py in line 536 to below

`
            with open(f"{name}", "w+") as out:
                out.write(self.html)
                webbrowser.open(f"{name}")
`

**Comment by lokeshsk** [comment]
```
Do not find the given graph file: 
Error: [Errno 2] No such file or directory: '/home/rd/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/SpatialAnalysisAgent-master/graphs/centroid_table.graphml'
Traceback (most recent call last):
  File "/home/rd/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/SpatialAnalysisAgent-master/SpatialAnalysisAgent_dockwidget.py", line 1295, in run
    exec(script_content, exec_globals, exec_locals)
  File "<string>", line 254, in <module>
  File "<class 'networkx.utils.decorators.argmap'> compilation 6", line 3, in argmap_read_graphml_1
    import gzip
                
  File "/var/data/python/lib/python3.12/site-packages/networkx/utils/decorators.py", line 198, in _open_file
    fobj = _dispatch_dict[ext](path, mode=mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/rd/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/SpatialAnalysisAgent-master/graphs/centroid_table.graphml'
The script finished with errors.
```
