### ISSUE TITLE
ModuleNotFoundError: No module named 'iface' 

### ISSUE THREAD

**Issue by bhf-love-lxy-forever** [Teakinboyewa/SpatialAnalysisAgent#22]
Does anyone know the reason for this ？

Couldn't load plugin 'SpatialAnalysisAgent-master' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'iface' 
Traceback (most recent call last):
  File "D:\Program Files/QGIS 3.34.13/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/BHF/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SpatialAnalysisAgent-master\__init__.py", line 35, in classFactory
    from .SpatialAnalysisAgent import SpatialAnalysisAgent
  File "D:\Program Files/QGIS 3.34.13/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/BHF/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SpatialAnalysisAgent-master\SpatialAnalysisAgent.py", line 31, in 
    from .SpatialAnalysisAgent_dockwidget import SpatialAnalysisAgentDockWidget
  File "D:\Program Files/QGIS 3.34.13/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/BHF/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SpatialAnalysisAgent-master\SpatialAnalysisAgent_dockwidget.py", line 32, in 
    import iface
  File "D:\Program Files/QGIS 3.34.13/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'iface'

Python version: 3.12.7 (main, Oct 25 2024, 11:18:09) [MSC v.1938 64 bit (AMD64)] 
QGIS version: 3.34.13-Prizren Prizren, 222b5995 

Python Path:
D:/Program Files/QGIS 3.34.13/apps/qgis-ltr/./python
C:/Users/BHF/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/BHF/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
D:/Program Files/QGIS 3.34.13/apps/qgis-ltr/./python/plugins
D:\Program Files\QGIS 3.34.13\apps\grass\grass84\etc\python
C:\Users\BHF\Documents
D:\Program Files\QGIS 3.34.13\bin\python312.zip
D:\Program Files\QGIS 3.34.13\apps\Python312\DLLs
D:\Program Files\QGIS 3.34.13\apps\Python312\Lib
D:\Program Files\QGIS 3.34.13\bin
D:\Program Files\QGIS 3.34.13\apps\Python312
D:\Program Files\QGIS 3.34.13\apps\Python312\Lib\site-packages
D:\Program Files\QGIS 3.34.13\apps\Python312\Lib\site-packages\win32
D:\Program Files\QGIS 3.34.13\apps\Python312\Lib\site-packages\win32\lib
D:\Program Files\QGIS 3.34.13\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/BHF/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by bhf-love-lxy-forever** [comment]
Couldn't load plugin 'SpatialAnalysisAgent-master' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'iface' 
Traceback (most recent call last):
  File "D:\Program Files/QGIS 3.34.13/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/BHF/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SpatialAnalysisAgent-master\__init__.py", line 35, in classFactory
    from .SpatialAnalysisAgent import SpatialAnalysisAgent
  File "D:\Program Files/QGIS 3.34.13/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/BHF/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SpatialAnalysisAgent-master\SpatialAnalysisAgent.py", line 31, in 
    from .SpatialAnalysisAgent_dockwidget import SpatialAnalysisAgentDockWidget
  File "D:\Program Files/QGIS 3.34.13/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/BHF/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SpatialAnalysisAgent-master\SpatialAnalysisAgent_dockwidget.py", line 32, in 
    import iface
  File "D:\Program Files/QGIS 3.34.13/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'iface'


Python version: 3.12.7 (main, Oct 25 2024, 11:18:09) [MSC v.1938 64 bit (AMD64)] 
QGIS version: 3.34.13-Prizren Prizren, 222b5995 

Python Path:
D:/Program Files/QGIS 3.34.13/apps/qgis-ltr/./python
C:/Users/BHF/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/BHF/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
D:/Program Files/QGIS 3.34.13/apps/qgis-ltr/./python/plugins
D:\Program Files\QGIS 3.34.13\apps\grass\grass84\etc\python
C:\Users\BHF\Documents
D:\Program Files\QGIS 3.34.13\bin\python312.zip
D:\Program Files\QGIS 3.34.13\apps\Python312\DLLs
D:\Program Files\QGIS 3.34.13\apps\Python312\Lib
D:\Program Files\QGIS 3.34.13\bin
D:\Program Files\QGIS 3.34.13\apps\Python312
D:\Program Files\QGIS 3.34.13\apps\Python312\Lib\site-packages
D:\Program Files\QGIS 3.34.13\apps\Python312\Lib\site-packages\win32
D:\Program Files\QGIS 3.34.13\apps\Python312\Lib\site-packages\win32\lib
D:\Program Files\QGIS 3.34.13\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/BHF/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by bhf-love-lxy-forever** [comment]
Solution：
in C:\Users\user1\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\SpatialAnalysisAgent-masterSpatialAnalysisAgent_dockwidget.py

line 32
## import iface
